# backend/api/card_generator.py
"""
Kit Card Generator - Produces output in multiple formats
"""

import json
from datetime import datetime
from typing import Dict, Optional
from pathlib import Path
import markdown
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT


class CardGenerator:
    """Generate kit cards in various formats (Markdown, JSON, PDF)"""
    
    def __init__(self, output_dir: str = "./output"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
    
    def generate_markdown(self, card_data: Dict) -> str:
        """Generate a Markdown kit card"""
        
        md_content = f"""# Kit Card: {card_data['part_name']}

---

## Part Information

**Part Name:** {card_data['part_name']}  
**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}  
**File Hash:** `{card_data['file_hash'][:16]}...`

---

## Geometric Properties

| Property | Value |
|----------|-------|
| **Volume** | {card_data['volume_cm3']:.2f} cm³ |
| **Mass** | {card_data['mass_g']:.2f} g |
| **Bounding Box** | {card_data['bounding_box'][0]:.1f} × {card_data['bounding_box'][1]:.1f} × {card_data['bounding_box'][2]:.1f} mm |
| **Surface Area** | {card_data['surface_area_cm2']:.2f} cm² |

---

## Mesh Quality

| Property | Value |
|----------|-------|
| **Triangle Count** | {card_data['triangle_count']:,} |
| **Watertight** | {'✅ Yes' if card_data['is_watertight'] else '⚠️ No'} |
| **Shell Count** | {card_data['shell_count']} |
| **Complexity Score** | {card_data['complexity_score']}/10 |

---

## Cost Analysis

| Item | Value |
|------|-------|
| **Material Cost** | ${card_data['est_material_cost']:.2f} USD |
| **Estimated Print Time** | {card_data['est_print_time_hours']:.2f} hours |

---

## Recommended Print Settings

| Setting | Value |
|---------|-------|
| **Layer Height** | {card_data['recommended_layer_height']:.2f} mm |
| **Infill** | {card_data['recommended_infill']}% |

---

## Assembly Notes

*This section is reserved for manual assembly instructions and notes.*

---

**Generated by KitForge MVP** | *Engineering rituals, automated*
"""
        
        # Save to file
        filename = f"{card_data['part_name'].replace(' ', '_')}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
        filepath = self.output_dir / filename
        
        with open(filepath, 'w') as f:
            f.write(md_content)
        
        return str(filepath)
    
    def generate_json(self, card_data: Dict) -> str:
        """Generate a JSON kit card"""
        
        # Add metadata
        output_data = {
            **card_data,
            'generated_at': datetime.now().isoformat(),
            'format_version': '1.0',
            'generator': 'KitForge MVP'
        }
        
        # Save to file
        filename = f"{card_data['part_name'].replace(' ', '_')}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
        filepath = self.output_dir / filename
        
        with open(filepath, 'w') as f:
            json.dump(output_data, f, indent=2)
        
        return str(filepath)
    
    def generate_pdf(self, card_data: Dict) -> str:
        """Generate a PDF kit card (paid tier only)"""
        
        filename = f"{card_data['part_name'].replace(' ', '_')}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
        filepath = self.output_dir / filename
        
        # Create PDF document
        doc = SimpleDocTemplate(str(filepath), pagesize=letter)
        story = []
        styles = getSampleStyleSheet()
        
        # Custom styles
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#1a1a1a'),
            spaceAfter=30,
            alignment=TA_CENTER
        )
        
        heading_style = ParagraphStyle(
            'CustomHeading',
            parent=styles['Heading2'],
            fontSize=16,
            textColor=colors.HexColor('#2c3e50'),
            spaceAfter=12,
            spaceBefore=12
        )
        
        # Title
        story.append(Paragraph(f"Kit Card: {card_data['part_name']}", title_style))
        story.append(Spacer(1, 0.2*inch))
        
        # Preview image if available
        if card_data.get('preview_image_path') and Path(card_data['preview_image_path']).exists():
            try:
                img = Image(card_data['preview_image_path'], width=4*inch, height=3*inch)
                story.append(img)
                story.append(Spacer(1, 0.3*inch))
            except:
                pass
        
        # Part Information
        story.append(Paragraph("Part Information", heading_style))
        info_data = [
            ['Generated:', datetime.now().strftime('%Y-%m-%d %H:%M:%S')],
            ['File Hash:', card_data['file_hash'][:16] + '...'],
        ]
        info_table = Table(info_data, colWidths=[2*inch, 4*inch])
        info_table.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('TEXTCOLOR', (0, 0), (0, -1), colors.HexColor('#555555')),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ]))
        story.append(info_table)
        story.append(Spacer(1, 0.2*inch))
        
        # Geometric Properties
        story.append(Paragraph("Geometric Properties", heading_style))
        geo_data = [
            ['Volume:', f"{card_data['volume_cm3']:.2f} cm³"],
            ['Mass:', f"{card_data['mass_g']:.2f} g"],
            ['Bounding Box:', f"{card_data['bounding_box'][0]:.1f} × {card_data['bounding_box'][1]:.1f} × {card_data['bounding_box'][2]:.1f} mm"],
            ['Surface Area:', f"{card_data['surface_area_cm2']:.2f} cm²"],
        ]
        geo_table = Table(geo_data, colWidths=[2*inch, 4*inch])
        geo_table.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('TEXTCOLOR', (0, 0), (0, -1), colors.HexColor('#555555')),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
        ]))
        story.append(geo_table)
        story.append(Spacer(1, 0.2*inch))
        
        # Mesh Quality
        story.append(Paragraph("Mesh Quality", heading_style))
        quality_data = [
            ['Triangle Count:', f"{card_data['triangle_count']:,}"],
            ['Watertight:', '✓ Yes' if card_data['is_watertight'] else '✗ No'],
            ['Shell Count:', str(card_data['shell_count'])],
            ['Complexity Score:', f"{card_data['complexity_score']}/10"],
        ]
        quality_table = Table(quality_data, colWidths=[2*inch, 4*inch])
        quality_table.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('TEXTCOLOR', (0, 0), (0, -1), colors.HexColor('#555555')),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
        ]))
        story.append(quality_table)
        story.append(Spacer(1, 0.2*inch))
        
        # Cost Analysis
        story.append(Paragraph("Cost Analysis", heading_style))
        cost_data = [
            ['Material Cost:', f"${card_data['est_material_cost']:.2f} USD"],
            ['Print Time:', f"{card_data['est_print_time_hours']:.2f} hours"],
        ]
        cost_table = Table(cost_data, colWidths=[2*inch, 4*inch])
        cost_table.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (-1, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 11),
            ('TEXTCOLOR', (0, 0), (-1, -1), colors.HexColor('#2c3e50')),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#2c3e50')),
            ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#ecf0f1')),
        ]))
        story.append(cost_table)
        story.append(Spacer(1, 0.2*inch))
        
        # Recommended Settings
        story.append(Paragraph("Recommended Print Settings", heading_style))
        settings_data = [
            ['Layer Height:', f"{card_data['recommended_layer_height']:.2f} mm"],
            ['Infill:', f"{card_data['recommended_infill']}%"],
        ]
        settings_table = Table(settings_data, colWidths=[2*inch, 4*inch])
        settings_table.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('TEXTCOLOR', (0, 0), (0, -1), colors.HexColor('#555555')),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
        ]))
        story.append(settings_table)
        story.append(Spacer(1, 0.3*inch))
        
        # Footer
        footer_style = ParagraphStyle(
            'Footer',
            parent=styles['Normal'],
            fontSize=9,
            textColor=colors.grey,
            alignment=TA_CENTER
        )
        story.append(Spacer(1, 0.5*inch))
        story.append(Paragraph("Generated by KitForge MVP | Engineering rituals, automated", footer_style))
        
        # Build PDF
        doc.build(story)
        
        return str(filepath)
    
    def generate_card(
        self,
        card_data: Dict,
        format: str = 'markdown',
        include_preview: bool = True
    ) -> str:
        """
        Generate a kit card in the specified format
        
        Args:
            card_data: Dictionary containing all card data
            format: Output format ('markdown', 'json', 'pdf')
            include_preview: Whether to include preview image
        
        Returns:
            Path to generated file
        """
        if format.lower() == 'markdown':
            return self.generate_markdown(card_data)
        elif format.lower() == 'json':
            return self.generate_json(card_data)
        elif format.lower() == 'pdf':
            return self.generate_pdf(card_data)
        else:
            raise ValueError(f"Unsupported format: {format}")


# Singleton instance
card_generator = CardGenerator()
